# Generated by Django 6.0.3 on 2026-03-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
