# Generated by Django 6.0.3 on 2026-03-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('IT', 'Italian'), ('GR', 'Greek'), ('MX', 'Mexican'), ('FF', 'Fast Food'), ('OT', 'OTHER')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
