# Generated by Django 6.0.3 on 2026-03-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0004_sales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
