# Generated by Django 6.0.3 on 2026-03-17 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0006_alter_restaurant_restaurant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='date_opened',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
