# Generated by Django 6.0.3 on 2026-03-23 14:12

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0008_rename_date_time_sale_datetime_alter_rating_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
