# Generated by Django 6.0.3 on 2026-03-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0009_alter_restaurant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('restaurant', models.ManyToManyField(to='ORM.restaurant')),
            ],
        ),
    ]
